// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var welcome = Welcome.FromJson(jsonString);

using System.Collections.Generic;
using Newtonsoft.Json;

namespace PoeCraftLib.Data.Entities
{
    public partial class BaseItemJson
    {
        public string FullName { get; set; }

        [JsonProperty("domain")]
        public string Domain { get; set; }

        [JsonProperty("drop_level")]
        public long DropLevel { get; set; }

        [JsonProperty("implicits")]
        public List<string> Implicits { get; set; }

        [JsonProperty("inventory_height")]
        public long InventoryHeight { get; set; }

        [JsonProperty("inventory_width")]
        public long InventoryWidth { get; set; }

        [JsonProperty("item_class")]
        public string ItemClass { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("properties")]
        public Dictionary<string, string> Properties { get; set; }

        [JsonProperty("release_state")]
        public string ReleaseState { get; set; }

        [JsonProperty("requirements")]
        public Requirements Requirements { get; set; }

        [JsonProperty("tags")]
        public List<string> Tags { get; set; }

        [JsonProperty("visual_identity")]
        public VisualIdentity VisualIdentity { get; set; }

        [JsonProperty("grants_buff", NullValueHandling = NullValueHandling.Ignore)]
        public ItemGrantsBuff GrantsBuff { get; set; }
    }

    public partial class ItemGrantsBuff
    {
        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("stats")]
        public Dictionary<string, long> Stats { get; set; }
    }

    public partial class Requirements
    {
        [JsonProperty("dexterity")]
        public long Dexterity { get; set; }

        [JsonProperty("intelligence")]
        public long Intelligence { get; set; }

        [JsonProperty("level")]
        public long Level { get; set; }

        [JsonProperty("strength")]
        public long Strength { get; set; }
    }

    public partial class VisualIdentity
    {
        [JsonProperty("dds_file")]
        public string DdsFile { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; }
    }
}